### ISSUE TITLE
Maintenance tasks

### ISSUE THREAD

**Issue by mdpiper** [permamodel/permamodel#77]
This is list of tasks to be completed to help make *permamodel* easier to maintain over time.

- [x] Move CI to GitHub Actions, #73
- [x] Use pyproject.toml for project metadata, #75
- [x] Use *nox* for building and testing project, #76
- [x] Add tests for Ku, #79 
- [x] Fix #72, which is not tested
- [x] Fix #32
- [ ] Fix #78 
- [ ] Move tests out of package?
- [x] Test BMI, #80 
- [x] Remove obsolete (?) `.bmi/` and `.bmi.yaml`
- [x] Add citation file
- [x] Add a changelog
- [x] Set up MANIFEST.in, check build files, #81
- [x] Make a new release
- [x] Upload release to PyPI
- [x] Check permamodel recipe on conda-forge
- [x] Check pymt_permamodel
